name: dlib
channels:
  - conda-forge
dependencies:
  - streamlit
  - dlib
  - numpy
  - scipy
  - opencv
  - face_recognition
  - streamlit-cropper==0.2.0
  - watchdog==2.1.9
  - plotly==5.9.0
  - matplotlib==3.5.2
  - mtcnn==0.1.1
  - tensorflow==2.9.1
  - pafy==0.5.5
  - youtube-dl==2020.12.2
  - scikit_image==0.19.3
  - torch==1.12.0
  - torchvision==0.13.0
  - facenet_pytorch==2.5.2
  - torchsummary==1.5.1
  - mmcv==1.5.3
  - timm==0.5.4
  - albumentations==1.2.0
  - iopath==-0.1.9
  - simplejson==3.17.6
  - fvcore==-0.1.5.post20220512